"""registra se o treino substituiu o modelo

Revision ID: 1c1a45336567
Revises: 68c265401469
Create Date: 2026-09-22 19:39:50.763302

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c1a45336567"
down_revision: str | Sequence[str] | None = "68c265401469"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("treino", sa.Column("substituiu", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("treino", "substituiu")
    # ### end Alembic commands ###
