"""cria tabela treino

Revision ID: 68c265401469
Revises: 6bb179001a28
Create Date: 2026-09-21 17:43:59.840215

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68c265401469"
down_revision: str | Sequence[str] | None = "6bb179001a28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "treino",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pendente",
                "rodando",
                "concluido",
                "falhou",
                name="status_treino",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("f1_macro", sa.Float(), nullable=True),
        sa.Column("desvio", sa.Float(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("qtd_exemplos", sa.Integer(), nullable=True),
        sa.Column("erro", sa.String(length=500), nullable=True),
        sa.Column(
            "iniciado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("terminado_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("treino")
    # ### end Alembic commands ###
