"""cria tabela predicao

Revision ID: c230926932e4
Revises:
Create Date: 2026-09-21 16:33:59.137799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c230926932e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predicao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.String(length=1000), nullable=False),
        sa.Column("label", sa.Integer(), nullable=False),
        sa.Column("confianca", sa.Float(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predicao")
    # ### end Alembic commands ###
